site/main/urls.py
"""
 This file was created on October 15th, 2016
 by Deborah Venuti and James Riley

 Last updated on: November 21st, 2016
 Updated by: Bethany Sanders
"""

from django.conf.urls import url
from django.contrib.auth.views import logout
from django.contrib.auth.views  import password_reset_done
from django.contrib.auth.views  import password_reset
from django.contrib.auth.views  import password_reset_confirm
from django.contrib.auth.views  import password_reset_complete

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about$', views.about, name='about'),
    url(r'^profile$', views.profile, name='profile'),
    url(r'^encrypt$', views.encrypt, name='encrypt'),
    url(r'^decrypt$', views.decrypt, name='decrypt'),
    url(r'^signin$', views.signin, name='signin'),
    url(r'^signout$', logout, {'next_page': '/'}, name='signout'),
    url(r'^register$', views.register, name='register'),
    url(r'^resetpassword/passwordsent$', password_reset_done, name = 'password_reset_done'),
    url(r'^resetpassword/$', password_reset, name = 'password_reset'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, name = 'password_reset_confirm'),
    url(r'^reset/done$', password_reset_complete, name = 'password_reset_complete'),
]

site/stegasaurus/urls.py
"""stegasaurus URL Configuration
The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import include, url
from django.contrib import admin

from django.conf.urls.static import static #For testing
from django.conf import settings #For testing

urlpatterns = [
    url(r'^', include('main.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #For testing

site/main/models.py
"""
 This file was created on October 15th, 2016
 by Deborah Venuti

 Contributors: Deborah Venuti, Gene Ryasnianskiy, Alexander Sumner

Last updated on: November 30, 2016
Updated by: Alexander Sumner
"""

from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

# Gene Ryasnianskiy added image model
class stegaImage(models.Model):
    def user_directory_path(instance, filename):
        # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
        return 'user_{0}/{1}'.format(instance.uploader.id, filename)
    
    uploader = models.ForeignKey(User, unique=False)
    FinalImage = models.ImageField(upload_to=user_directory_path)
    BaseImage = models.ImageField(upload_to=user_directory_path)
    TarFile = models.FileField(upload_to=user_directory_path)
    Created_on = models.DateTimeField(default = datetime.now)
    processType = models.CharField(max_length=256, default = 'Legacy')
      
#Alexander Sumner added extracted file model
class tempFile(models.Model):
    def user_directory_path(instance, filename):
        # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
        return 'user_{0}/{1}'.format(instance.uploader.id, filename)
    
    uploader = models.ForeignKey(User, unique=False)
    file = models.FileField(upload_to=user_directory_path)

site/main/forms.py
"""
 This file was created on October 15th, 2016
 by Deborah Venuti

 Contributors: Deborah Venuti, Gene Ryasnianskiy, Alexander Sumner


 Last updated on: November 20, 2016
 Updated by: Gene Ryasnianskiy
"""

from django import forms
from multiupload.fields import MultiFileField

class RegisterForm(forms.Form):
    first_name = forms.CharField(label='First Name', max_length=100)
    last_name = forms.CharField(label='Last Name', max_length=100)
    email = forms.EmailField(label='Email', max_length=150)
    password = forms.CharField(label='Password', max_length=32, widget=forms.PasswordInput)

class SignInForm(forms.Form):
    email = forms.EmailField(label='Email', max_length=150)
    password = forms.CharField(max_length=32, widget=forms.PasswordInput)

# Added: Gene Ryasnianskiy October 31, 2016
class TextForm(forms.Form):
    carrier = forms.ImageField()
    text = forms.CharField(widget=forms.Textarea)

class DecryptForm(forms.Form):
    TEXT = 'T'
    FILE = 'F'
    carrier = forms.ImageField(label='Encrypted Image')
    choice = forms.ChoiceField(
        choices = (
            (TEXT, 'Decrypt Text'),
            (FILE, 'Decrypt File')
            )
        )

class MultipleDataForm(forms.Form):
    carrier = forms.ImageField(label='Carrier File')
    Files = MultiFileField(label='Data Files')

#Added: Gene Ryasnianskiy November 20, 2016
class DeleteFileForm(forms.Form):
    delete = forms.MultipleChoiceField(
        #choices = LIST_OF_VALID_CHOICES,
        widget  = forms.CheckboxSelectMultiple,
    )

site/main/views.py
"""
 This file was created on October 15th, 2016
 by Deborah Venuti, Bethany Sanders and James Riley

 Contributors: Deborah Venuti, Bethany Sanders,
  James Riley, Gene Ryasnianskiy, Alexander Sumner

Last updated on: November 30, 2016
Updated by: Alexander Sumner
"""

#Python Imports
import tarfile
import os

#Django Imports
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.files.base import ContentFile
from django.core.files import File
from django.shortcuts import render, render_to_response, reverse
from django.shortcuts import get_object_or_404
from django.views.generic.edit import FormView
from stegasaurus.settings import MEDIA_ROOT

#App Imports
from .models import stegaImage, tempFile
from .forms import RegisterForm, SignInForm, TextForm, DecryptForm, MultipleDataForm, DeleteFileForm
from . import stega

def index(request):
    return render(request, 'main/index.html')

def about(request):
    title = 'About'
    return render(request, 'main/about.html', {'title': title})

# Deborah Venuti added login_required decorator
# Gene Ryasnianskiy added archive display and delete logic
@login_required(login_url='/signin')
def profile(request):
    title = 'Profile'

    #Get user's files
    archiveFiles = stegaImage.objects.all().filter(uploader = request.user)

    #Form for deleting archive items
    if (request.method == 'POST'):
        delete_file_form = DeleteFileForm(request.POST)

        #Delete each item and each file by ID
        for itemID in request.POST.getlist('delete'):
            objToDelete = stegaImage.objects.get(id=itemID)
            try:
                os.remove(os.path.join(MEDIA_ROOT, objToDelete.FinalImage.name))
            except:
                pass
            try:
                os.remove(os.path.join(MEDIA_ROOT, objToDelete.BaseImage.name))
            except:
                pass
            try:
                os.remove(os.path.join(MEDIA_ROOT, objToDelete.TarFile.name))
            except:
                pass
            objToDelete.delete()

    else:
        delete_file_form = DeleteFileForm()

    context = {
        'title': title,
        'archive': archiveFiles,
        'delete_file_form': delete_file_form,
        }

    return render(request, 'main/profile.html', context)

# Deborah Venuti added this
# Gene Ryasnianskiy image upload and processing
# Alex Sumner modified to accept multiple images and tar them
# Gene Ryasnaksiy moved documents display to archive in profile view
@login_required(login_url='/signin')
def encrypt(request):
    title = 'Encrypt'

    userObject = User.objects.get(username = request.user.username)
    text_invalid = False
    file_invalid = False

    # Handle file upload
    if request.method == 'POST':

        #create form objects
        multiple_data_form = MultipleDataForm(request.POST, request.FILES)
        text_form = TextForm(request.POST, request.FILES)


        #form for gathering files and inserting them into a carrier
        if multiple_data_form.is_valid():

            #grab the information from the submitted form
            output = ContentFile(bytes(0))
            carrier = multiple_data_form.cleaned_data['carrier']
            tFile = tarfile.open("Data.tar", 'w:gz')

            #temporarily store the files to facilitate taring them later
            for each in multiple_data_form.cleaned_data['Files']:
                newfile = tempFile(uploader=request.user)
                newfile.file.save(each.name, each)
                tFile.add(("./static" + newfile.file.url), arcname=each.name)
                os.remove(os.path.join(MEDIA_ROOT, newfile.file.name))
                newfile.delete()

            #close the tar file
            tFile.close()

            #open file opject to grab the tar file
            data = open('Data.tar', mode = 'r+b')
            datas = File(data)

            #insert the data into the carrier
            try:
                stega.inject_file(carrier, datas.file , output)
                #save the steganographed image to the users database
                newimage = stegaImage(uploader=request.user, processType='Encrypt File')
                newimage.FinalImage.save(carrier.name, output)
                newimage.BaseImage.save(carrier.name, carrier)
                newimage.TarFile.save(datas.name, datas.file)

                #close the file objects and delete the temp tar file
                datas.close()
                data.close()
                os.remove(data.name)
                
                #return to the page
                return HttpResponseRedirect(reverse('profile'))

            except stega.ByteOperationError as e:
                file_invalid = True


        #form for text insertion
        if text_form.is_valid():

            #grab information from the submitted form
            output = ContentFile(bytes(0))
            carrier = text_form.cleaned_data['carrier']
            text = text_form.cleaned_data['text']

            #inject the text into the image
            try:
                stega.inject_text(carrier, text , output)
                #save the steganographed image into the users database
                new = stegaImage(uploader=request.user, processType='Encrypt Text')
                new.FinalImage.save(carrier.name, output)
                new.BaseImage.save(carrier.name, carrier)
                
                #return to the page
                return HttpResponseRedirect(reverse('profile'))
            
            except stega.ByteOperationError as e:
                text_invalid = True

    else:
        #set defaults for when no data has been submitted
        multiple_data_form = MultipleDataForm()
        text_form = TextForm()

    #create list of information to send over the the .html file
    context = {
        'multiple_data_form': multiple_data_form,
        'text_form': text_form,
        'title': title,
        'text_invalid': text_invalid,
        'file_invalid': file_invalid,
        }

    #load the page
    return render(request, 'main/encrypt.html', context)


#Alexander Sumner - tab for decrypting images
@login_required(login_url='/signin')
def decrypt(request):
    title = 'Decrypt'

    #gather user information
    userObject = User.objects.get(username = request.user.username)
    message = ''

    if (request.method == 'POST'):

        decrypt_form = DecryptForm(request.POST, request.FILES)

        if decrypt_form.is_valid():
            #form for extracting text
            if decrypt_form.cleaned_data['choice'] == decrypt_form.TEXT :
                #initialize data and grab the encrypted message
                carrier = decrypt_form.cleaned_data['carrier']
                message = stega.extract_text(carrier)
                
                #create a text file to save the message
                textfile = open("Decrypted_Text.txt", "w")
                textfile.write(message)
                textfile.close()
                data = open("Decrypted_Text.txt", mode = 'r+b')
                datas = File(data)
                
                #create a database entry for the decrypted text
                new = stegaImage(uploader=request.user, processType='Decrypt Text')
                new.BaseImage.save(carrier.name, carrier)
                new.TarFile.save(datas.name, datas.file)

                #close and remove the temp txt file
                datas.close()
                data.close()
                os.remove(data.name)

            #form for extracting files
            elif decrypt_form.cleaned_data['choice'] == decrypt_form.FILE :
                output = ContentFile(bytes(0))
                carrier = decrypt_form.cleaned_data['carrier']

                #extracting is currently in development
                stega.extract_file(carrier, output)

                #save the extracted file to the users database
                new = stegaImage(uploader=request.user, processType='Decrypt File')
                new.BaseImage.save(carrier.name, carrier)
                new.TarFile.save('Data.tar', output)

                return HttpResponseRedirect(reverse('profile'))


    else:
        decrypt_form = DecryptForm()


    context = {
        'decrypt_form': decrypt_form,
        'title': title,
        'message': message,
        }

    return render(request, 'main/decrypt.html', context)



# Deborah Venuti added return of invalid indicator for sign in attempt of non-existing account
def signin(request):
    title = 'Sign In'

    if (request.method == 'POST'):
        form = SignInForm(request.POST)
        if form.is_valid():
            formData = form.cleaned_data
            userName = formData['email']
            userPassword = formData['password']

            user = authenticate(username=userName, password=userPassword)
            print(user)
            if (user is not None):
                login(request,user)
                return HttpResponseRedirect('/profile')
            else:
                return render(request, 'main/signin.html', {'form':form, 'invalid': True})
        else:
             return render(request, 'main/signin.html', {'form':form, 'invalid': True})

    else:
        form = SignInForm()
    return render(request, 'main/signin.html', {'form': form, 'title': title})

def register(request):
    title = 'Register'

    if (request.method == 'POST'):
        form = RegisterForm(request.POST)
        if form.is_valid():
            formData = form.cleaned_data

            try:
                user = User.objects.get(username=formData['email'])
                if (user is not None):
                    return render(request, 'main/register.html', {'form':form, 'invalid': True})

            except User.DoesNotExist:

site/main/templates/main/about.html
<!--
 This file was created on November 28th, 2016
 by James Riley

 Last updated on: November 29, 2016
 Updated by: James Riley
-->

{% extends 'main/base.html' %}
{% load static %}

{% block content %}
<header id="top" class="header">
 	<div class="inner cover">
    	<div class="col-md-12 col-centered well">
        	<div class="text-center">
        		<h3>About Stegasaurus</h3>
        	</div>
        	<p>Stegasaurus is a web-based image steganography tool. Here users can encrypt images and text into a larger image file as well as decrypt images which have already had images or text encrypted into them.</p> 
        	<p>Stegasaurus users can upload an image which they wish to have a smaller image or string of text encrypted into. The uploaded images and strings of text are processed into arrays of bytes. The bits comprising the bytes of the smaller image or text are then used to sequentially replace the least significant bits of the larger image's bytes. Because only the least significant bits are modified in the larger picture, the result is that the larger picture looks unchanged when the process is completed.</p>
        	<p>If a Stegasaurus user wishes to decrypt an image previously encrypted with Stegasaurus, they can upload their image at the Decrypt page and choose whether they are decrypting an image or text. The image is processed into an array of bytes. The least significant bits or each byte are sequentially copied into the bytes of another array which is then processed into an image or string of text depending on the user's selection at the Decrypt page.</p>
    	</div>
	</div>
</header>

{% endblock content %}
<!-- end body content block -->


<!-- begin script  block -->

<!-- end script block -->

site/main/templates/main/base.html
<!--
 This file was created on November 20, 2016
 by Deborah Venuti

 Last updated on: November 20, 2016
 Updated by: Deborah Venuti
-->

<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <link rel="icon" href="#">

        {% if title %}
        <title> Stegasaurus | {{ title }} </title>
        {% else %}
        <title> Stegasaurus </title>
        {% endif %}

        <!-- Bootstrap core CSS -->
        <link href="{% static 'main/css/bootstrap.min.css' %}" type="text/css" rel="stylesheet">

        <!-- Custom styles for this template -->
        <link href="{% static 'main/css/custom.css' %}" rel="stylesheet">
        <link href="{% static 'main/css/base.css' %}" rel="stylesheet">
    </head>

    <body>
        <div class="site-wrapper">
            <div class="cover-container">
                <div class="inner">
                    <h3 class="masthead-brand"><a href="/">Stegasaurus</a></h3>
                    {% if user.is_authenticated %}
                    <nav>
                        <ul class="nav masthead-nav">
                            <li {% if request.path == "/profile" %}class="active"{% endif %}><a href="/profile">Profile</a></li>
                            <li {% if request.path == "/encrypt" %}class="active"{% endif %}><a href="/encrypt">Encrypt</a></li>
                            <li {% if request.path == "/decrypt" %}class="active"{% endif %}><a href="/decrypt">Decrypt</a></li>
                            <li {% if request.path == "/about" %}class="active"{% endif %}><a href="/about">About</a></li>
                            <li><a href="/signout">Sign Out</a></li>
                        </ul>
                    </nav>
                    {% else %}
                    <nav>
                        <ul class="nav masthead-nav">
                            <li {% if request.path == "/" %}class="active"{% endif %}><a href="/">Home</a></li>
                            <li {% if request.path == "/about" %}class="active"{% endif %}><a href="/about">About</a></li>
                            <li {% if request.path == "/signin" %}class="active"{% endif %}><a href="/signin">Sign In</a></li>
                            <li {% if request.path == "/register" %}class="active"{% endif %}><a href="/register">Register</a></li>
                        </ul>
                    </nav>
                    {% endif %}
                    <div class="container">
                        <!-- begin body content block -->
                            {% block content %}
                            {% endblock %}
                        <!-- end body content block -->
                    </div>
                </div>
            </div>
        </div>





        <!-- begin script  block -->
            {% block javascript %}
            {% endblock %}
        <!-- end script block -->

    </body>
</html>

site/main/templates/main/decrypt.html
 <!--
 This file was created on November 3rd, 2016
 by Alexander Sumner

 Last updated on: November 30, 2016
 Updated by: James Riley
-->
{% extends 'main/base.html' %}
{% load static %}

{% block content %}
<header id="top" class="header">
    <div class="inner cover">
        <div class="col-md-3 col-centered"></div>
            <div class="col-md-12 col-centered well">
                <div class="text-center">
                     <h3>Decrypt</h3>
                      <p>Upload an image which has been encrypted by Stegasaurus and decrypt it to access its hidden data. If you aren't sure what each form expects, hover over the form label to see more information.</p>
                </div>
                <p>
                    <form enctype="multipart/form-data" method="post">
                        <div class="form-container">
                            {%  csrf_token %}
                            <p>
                                <label data-toggle="tooltip" title="Image previously encrypted with Stegasaurus" for="id_carrier">Encrypted File:</label>
                                <input id="id_carrier" name="carrier" type="file" required>
                            </p>
                            <p>
                                <label for="id_choice">Choice:</label>
                                <select id="id_choice" name="choice" required>
                                    <option value="T">Decrypt Text</option>
                                    <option value="F">Decrypt File</option>
                                </select>
                            </p>
                        </div>
                        <div class="text-center">
                            <input type="submit" class="btn btn-primary" value="Submit"/>
                        </div>
                        <p>{{ message }}</p>
                    </form>
                </p>
            </div>
        </div>
    </div>
</header>
{% endblock %}
<!-- end body content block -->

<!-- begin script  block -->
{% block javascript %}
    <script>
        $(document).ready(function(){
        $('[data-toggle="tooltip"]').tooltip();
        });
    </script>
{% endblock %}
<!-- end script block -->

site/main/templates/main/encrypt.html
<!--
 This file was created on October 28th, 2016
 by Deborah Venuti

 Contributors: Alexander Sumner

 Last updated on: November 30, 2016
 Updated by: James Riley
-->
{% extends 'main/base.html' %}
{% load static %}

{% block content %}
<header id="top" class="header">
    <div class="inner cover">
        <div class="col-md-3 col-centered"></div>
            <div class="col-md-12 col-centered well">
              <div class="text-center">
                 <h3>Encrypt</h3>
                 <p>Upload a carrier image and either upload data files or enter text for encryption. If you aren't sure what each form expects, hover over the form label to see more information.</p>
                 <button class="btn btn-primary" onclick="show('id1');"> Encrypt File</button>
                 <button class="btn btn-primary" onclick="show('id2');"> Encrypt Text</button>
              </div>
                 <p>
                  <div id="id1"  style="display:block">
                      <form enctype="multipart/form-data" method="post">
                      {% if file_invalid %}
                        <div class="text-center">
                          <p class="error-msg"> Carrier image is too small to hold the data. Upload a larger carrier image.</p>
                        </div>
                      {% endif %}
                        <div class="form-container">
                          {%  csrf_token %}
                          <p>
                            <label data-toggle="tooltip" title="Large image you wish to have data files encrypted into" for="id_carrier">Carrier File:</label>
                            <input id="id_carrier" name="carrier" required=" " type="file">
                          </p>
                          <p>
                            <label data-toggle="tooltip" title="File(s) you wish to have encrypted into the carrier image" for="id_Files">Data Files:</label>
                            <input id="id_Files" multiple="multiple" name="Files" required=" " type="file">
                          </p>
                        </div>
                        <div class="text-center">
                          <input type="submit" class="btn btn-primary" value="Submit"/>
                        </div>
                      </form>
                  </div>
                  <div id="id2"  style="display:none">
                    <form enctype="multipart/form-data" method="post">
                      {% if text_invalid %}
                        <div class="text-center">
                          <p class="error-msg"> Carrier image is too small to hold the data. Upload a larger carrier image.</p>
                        </div>
                      {% endif %}
                      <div class="form-container">
                        {%  csrf_token %}
                        <p>
                          <label data-toggle="tooltip" title="Large image you wish to have data files encrypted into" for="id_carrier">Carrier File:</label>
                          <input id="id_carrier" name="carrier" type="file" required>
                        </p>
                        <p>
                          <label data-toggle="tolltip" title="Text you wish to encrypt into the carrier image"for="id_text">Text:</label><br>
                          <textarea cols="30" id="id_text" name="text" rows="5" required></textarea>
                        </p>
                      </div>
                      <div class="text-center">
                        <input type="submit" class="btn btn-primary" value="Submit"/>
                      </div>
                    </form>
                  </div>
                 </p>
            </div>
        </div>
    </div>
</header>
{% endblock %}
<!-- end body content block -->

<!-- begin script  block -->
    {% block javascript %}
    <script type="text/javascript">
    function show(elementId) {
     document.getElementById("id1").style.display="none";
     document.getElementById("id2").style.display="none";
     document.getElementById(elementId).style.display="block";
    }
    </script>
    {% endblock %}
<!-- end script block -->

site/main/templates/main/profile.html
<!--
 This file was created on October 15th, 2016
 by Deborah Venuti and Bethany Sanders

 Last updated on: November 30, 2016
 Updated by: Alexander Sumner
-->
{% extends 'main/base.html' %}
{% load static %}

<!-- begin body content block -->
{% block content %}
<header id="top" class="header">
    <div class="inner cover">
        <div class="col-md-3 col-centered"></div>
            <div class="col-md-12 col-centered well">
            	<div class="text-center">
					 <h2>{{ user.first_name }} {{user.last_name}}</h2>
					 <button class="btn btn-primary" onclick="show('id1');"> Details </button>
					 <button id="archive" class="btn btn-primary" onclick="show('id2');"> Archive </button>

					 <p>
					 	<div id="id1"  style="display:none">
							<h4>Account Email:	{{user.email}}</h4>
              <div class = "other-link"><a href= "/resetpassword" >Reset Password</a></div>
						</div>
					 	<div id="id2"  style="display:block">
                            {% if archive %}

                            <form enctype="multipart/form-data" method="post">
                                {%  csrf_token %}

                                  <table class="table table-striped table-hover ">
                                  <thead>
                                    <tr>
                                      <th>Processing Date</th>
                                      <th>Job Type</th>
                                      <th>Files</th>
                                      <th>Select</th>
                                    </tr>
                                  </thead>
                                  <tbody>
                                    {% for files in archive %}
                                        <tr>
                                          <td align="left">{{ files.Created_on }} UTC</td>
                                          <td align="left">{{ files.processType }}</td>
                                          {% if files.processType == 'Decrypt File' or files.processType == 'Decrypt Text' %}
                                            <td align="left"> <span class="other-link">
                                              <a href="{{ files.TarFile.url }}">{{ files.TarFile }}</a>
                                            </span> </td>
                                          {% else %}
                                            <td align="left"> <span class="other-link">
                                                <a href="{{ files.FinalImage.url }}">{{ files.FinalImage }}</a>
                                            </span> </td>
                                          {% endif %}
                                          <td><input  id="id_delete" name="delete" type="checkbox" value="{{files.id}}" name="choices"></td>
                                        </tr>
                                    {% endfor %}
                                  </tbody>
                                </table>

                                <div class="text-right">
                                    <input type="submit" class="btn btn-primary" value="Delete"/>
                                </div>

                            </form>

                            {% else %}
                            <div class="text-center">
                                <p>No documents.</p>
                            </div>
                            {% endif %}

					 	</div>
					 </p>
				</div>
            </div>
        </div>
    </div>
</header>
{% endblock %}
<!-- end body content block -->

<!-- begin script  block -->
    {% block javascript %}
		<script type="text/javascript">
		function show(elementId) {
		 document.getElementById("id1").style.display="none";
		 document.getElementById("id2").style.display="none";
		 document.getElementById(elementId).style.display="block";
		}
		</script>
    {% endblock %}
<!-- end script block -->